/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemesIndexRouteImport } from './routes/themes/index'
import { Route as QuotesIndexRouteImport } from './routes/quotes/index'
import { Route as PhilosophersIndexRouteImport } from './routes/philosophers/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ThemesSlugRouteImport } from './routes/themes/$slug'
import { Route as PhilosophersTimelineRouteImport } from './routes/philosophers/timeline'
import { Route as PhilosophersSlugRouteImport } from './routes/philosophers/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses/$slug/index'
import { Route as CoursesSlugLessonSlugRouteImport } from './routes/courses/$slug/$lessonSlug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophersIndexRoute = PhilosophersIndexRouteImport.update({
  id: '/philosophers/',
  path: '/philosophers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/themes/$slug',
  path: '/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophersTimelineRoute = PhilosophersTimelineRouteImport.update({
  id: '/philosophers/timeline',
  path: '/philosophers/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophersSlugRoute = PhilosophersSlugRouteImport.update({
  id: '/philosophers/$slug',
  path: '/philosophers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugLessonSlugRoute = CoursesSlugLessonSlugRouteImport.update({
  id: '/$lessonSlug',
  path: '/$lessonSlug',
  getParentRoute: () => CoursesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/philosophers/$slug': typeof PhilosophersSlugRoute
  '/philosophers/timeline': typeof PhilosophersTimelineRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/philosophers/': typeof PhilosophersIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/philosophers/$slug': typeof PhilosophersSlugRoute
  '/philosophers/timeline': typeof PhilosophersTimelineRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/philosophers': typeof PhilosophersIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/themes': typeof ThemesIndexRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/philosophers/$slug': typeof PhilosophersSlugRoute
  '/philosophers/timeline': typeof PhilosophersTimelineRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/philosophers/': typeof PhilosophersIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/glossary'
    | '/login'
    | '/map'
    | '/search'
    | '/articles/$slug'
    | '/courses/$slug'
    | '/philosophers/$slug'
    | '/philosophers/timeline'
    | '/themes/$slug'
    | '/articles/'
    | '/courses/'
    | '/philosophers/'
    | '/quotes/'
    | '/themes/'
    | '/courses/$slug/$lessonSlug'
    | '/courses/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/glossary'
    | '/login'
    | '/map'
    | '/search'
    | '/articles/$slug'
    | '/philosophers/$slug'
    | '/philosophers/timeline'
    | '/themes/$slug'
    | '/articles'
    | '/courses'
    | '/philosophers'
    | '/quotes'
    | '/themes'
    | '/courses/$slug/$lessonSlug'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/glossary'
    | '/login'
    | '/map'
    | '/search'
    | '/articles/$slug'
    | '/courses/$slug'
    | '/philosophers/$slug'
    | '/philosophers/timeline'
    | '/themes/$slug'
    | '/articles/'
    | '/courses/'
    | '/philosophers/'
    | '/quotes/'
    | '/themes/'
    | '/courses/$slug/$lessonSlug'
    | '/courses/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  GlossaryRoute: typeof GlossaryRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  PhilosophersSlugRoute: typeof PhilosophersSlugRoute
  PhilosophersTimelineRoute: typeof PhilosophersTimelineRoute
  ThemesSlugRoute: typeof ThemesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PhilosophersIndexRoute: typeof PhilosophersIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophers/': {
      id: '/philosophers/'
      path: '/philosophers'
      fullPath: '/philosophers/'
      preLoaderRoute: typeof PhilosophersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/themes/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophers/timeline': {
      id: '/philosophers/timeline'
      path: '/philosophers/timeline'
      fullPath: '/philosophers/timeline'
      preLoaderRoute: typeof PhilosophersTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophers/$slug': {
      id: '/philosophers/$slug'
      path: '/philosophers/$slug'
      fullPath: '/philosophers/$slug'
      preLoaderRoute: typeof PhilosophersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/$lessonSlug': {
      id: '/courses/$slug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/courses/$slug/$lessonSlug'
      preLoaderRoute: typeof CoursesSlugLessonSlugRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface CoursesSlugRouteChildren {
  CoursesSlugLessonSlugRoute: typeof CoursesSlugLessonSlugRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugLessonSlugRoute: CoursesSlugLessonSlugRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  GlossaryRoute: GlossaryRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  PhilosophersSlugRoute: PhilosophersSlugRoute,
  PhilosophersTimelineRoute: PhilosophersTimelineRoute,
  ThemesSlugRoute: ThemesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PhilosophersIndexRoute: PhilosophersIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
